"""Ajouts d'informations sur le positionnement des valeurs dans différents cas

Revision ID: 36743f9614a5
Revises: c4ee3c9e42b6
Create Date: 2025-12-04 20:02:14.138200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36743f9614a5'
down_revision: Union[str, Sequence[str], None] = 'c4ee3c9e42b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('min_value', sa.Float(), nullable=True))
    op.add_column('action', sa.Column('max_value', sa.Float(), nullable=True))
    op.add_column('action', sa.Column('ssh_error_default_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action', 'ssh_error_default_value')
    op.drop_column('action', 'max_value')
    op.drop_column('action', 'min_value')
    # ### end Alembic commands ###
