"""Précision de l'unité et ajout de valeurs par défauts

Revision ID: 3b700ae84d39
Revises: 36743f9614a5
Create Date: 2025-12-04 20:03:55.754411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b700ae84d39'
down_revision: Union[str, Sequence[str], None] = '36743f9614a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('unite', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('action', sa.Column('rounding', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action', 'rounding')
    op.drop_column('action', 'unite')
    # ### end Alembic commands ###
