"""Ajout d'un champ labels aux Actions

Revision ID: 93b366b2469b
Revises: a415bc77f0d8
Create Date: 2025-12-05 15:25:25.955827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93b366b2469b'
down_revision: Union[str, Sequence[str], None] = 'a415bc77f0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('action', sa.Column('labels', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action', 'labels')
    # ### end Alembic commands ###
