"""Ajout d'un champ paramtres à un indicateur

Revision ID: a415bc77f0d8
Revises: 958f57917ac2
Create Date: 2025-12-05 14:45:19.800729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a415bc77f0d8'
down_revision: Union[str, Sequence[str], None] = '958f57917ac2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicator', sa.Column('parametre', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('indicator', 'parametre')
    # ### end Alembic commands ###
